const COUNTRY_LANGUAGE: Record<string, string> = {
  "united states": "en",
  usa: "en",
  "united kingdom": "en",
  uk: "en",
  canada: "en",
  australia: "en",
  ireland: "en",
  "new zealand": "en",
  singapore: "en",
  india: "en",
  germany: "de",
  austria: "de",
  switzerland: "de",
  france: "fr",
  spain: "es",
  mexico: "es",
  argentina: "es",
  colombia: "es",
  chile: "es",
  italy: "it",
  portugal: "pt",
  brazil: "pt",
  netherlands: "nl",
  belgium: "nl",
  sweden: "sv",
  norway: "no",
  denmark: "da",
  finland: "fi",
  poland: "pl",
  "czech republic": "cs",
  japan: "ja",
  "south korea": "ko",
  china: "zh",
  taiwan: "zh",
  "hong kong": "zh",
  vietnam: "vi",
  thailand: "th",
  indonesia: "id",
  malaysia: "ms",
  turkey: "tr",
  russia: "ru",
  "saudi arabia": "ar",
  uae: "ar",
  egypt: "ar",
};

/** Best-effort language guess from a country name, defaulting to English. */
export function guessLanguageFromCountry(country: string | null | undefined): string {
  if (!country) return "en";
  return COUNTRY_LANGUAGE[country.trim().toLowerCase()] ?? "en";
}
